package pe.com.gp.form;

import java.io.Serializable;
import org.apache.struts.action.ActionForm;

public class GenericoForm extends ActionForm implements Serializable {

    static final long serialVersionUID = 1L;
    private String operacion;

    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    // POR FAVOR NO AGREGAR MAS PROPIEDADES A ESTE FORM. SOLO DEBE TENER UNA PROPIEDAD. GRACIAS.
    public GenericoForm() {
    }

    public String getOperacion() {
        return operacion;
    }

    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }
}
